### ISSUE TITLE
URL issue without a server, and packaging discussion

### ISSUE THREAD

**Issue by allenhwkim** [ayushgp/web-components-tutorial#2]
https://rawgit.com/ayushgp/web-components-tutorial/master/Part%201/UserCard/UserCard.html

This should be changed to show it properly. e.g. ./UserCard/UserCard.js
```
<script src="/UserCard/UserCard.js"></script>
```

Also, what is your solution for packaging with lots of custom elements. e.g. 100s with separate js/css/html?

**Comment by ayushgp** [comment]
Hi @allenhwkim Sorry for the late reply. I've corrected the paths. I haven't looked at packaging web components yet. I don't have much idea about packaging. I think the following should work though:

A task runner can be used to concatenate all template tags and insert these in the DOM and remove the HTML import altogether from everywhere(They've been deprecated anyways). Also remove all script tags from the templates and concatenate all js files and load that file. Not so sure about the CSS though. 

I'll try out packaging components in a better way and update it here.

**Comment by allenhwkim** [comment]
Pioneering custom elements, I think It's not that easy based on experience of my project.

When components are released to public, every component should be packaged individually including polyfills. The problem is that existing polyfills are not so useful especially when it gets to performance.

Another one I had to consider is that I need to make a single package with related components together, so that users don't need to import every single packages. 

So far, for my project, Including polyfill, packaging, and all.
* Started exactly like you did,
* However, ended up with only using Custom Element, (no shadow DOM, no imports, or template)
* Built my own very simple customElements polyfill for performance.
* I found out that shadow DOM inserts its style on every single instance although they are exactly the same(I am not sure this affects performance).

Just wanted to share my experience ..

**Comment by ayushgp** [comment]
I also thought about that and seems that it is much more complex than what I first thought. 

Why aren't you using template tag though? Also what are you using in place of imports then?

**Comment by allenhwkim** [comment]
If I don't use Shadow DOM, the need of template disappears.

About Shadow DOM, it's good to have, but not necessary for building a custom elements. I use MutationObserver(because polyfill sucks), events. Shadow DOM is much more about  CSS isolation, I think.

If it is only about custom element, css isolation can be done with CSS.
