### ISSUE TITLE
'Forbidden' when running static-server

### ISSUE THREAD

**Issue by ysl208** [ayushgp/web-components-tutorial#4]
Hi, i just followed your instructions but after running static-server and going on localhost:9080 it shows a message Forbidden and nothing else.
Also the terminal shows

> * Static server successfully started.
> * Serving files at: http://localhost:9080
> * Press Ctrl+C to shutdown.
> <-- [GET] /
> --> 403 / (4.607ms)
> <-- [GET] /favicon.ico
> --> 404 /favicon.ico (0.706ms)
> <-- [GET] /favicon.ico
> --> 404 /favicon.ico (0.446ms)

any help?

**Comment by ayushgp** [comment]
Where are you running the static-server? You need to run it from inside
Part 1 or Part 2 folders, as the index files are located there. If you want
to run from root of the report, I think you'll have to provide the complete
url encoded path.

**Comment by ysl208** [comment]
Ah sorry, I didn't realise. No error this time but it is showing a blank screen 



De: "Ayush Gupta" <notifications@github.com> 
À: "ayushgp/web-components-tutorial" <web-components-tutorial@noreply.github.com> 
Cc: "ying-siu liang" <ying-siu.liang@univ-grenoble-alpes.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 17 Mai 2018 18:30:30 
Objet: Re: [ayushgp/web-components-tutorial] 'Forbidden' when running static-server (#4) 

Where are you running the static-server? You need to run it from inside 
Part 1 or Part 2 folders, as the index files are located there. If you want 
to run from root of the report, I think you'll have to provide the complete 
url encoded path.

**Comment by ayushgp** [comment]
Can you check the console logs?

Thanks,
Ayush Gupta

**Comment by ysl208** [comment]
* Static server successfully started. 
* Serving files at: http://localhost:9080 
* Press Ctrl+C to shutdown. 
<-- [GET] / 
--> 200 OK / (index.html) 279 Byte (10.742ms) 
<-- [GET] /UserCard/UserCard.html 
--> 200 OK /UserCard/UserCard.html 516 Byte (1.599ms) 
<-- [GET] /UserCard/UserCard.js 
--> 200 OK /UserCard/UserCard.js 2.7 KiB (3.171ms) 




De: "Ayush Gupta" <notifications@github.com> 
À: "ayushgp/web-components-tutorial" <web-components-tutorial@noreply.github.com> 
Cc: "ying-siu liang" <ying-siu.liang@univ-grenoble-alpes.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 17 Mai 2018 19:02:47 
Objet: Re: [ayushgp/web-components-tutorial] 'Forbidden' when running static-server (#4) 

Can you check the console logs? 

Thanks, 
Ayush Gupta

**Comment by ayushgp** [comment]
I meant the browser console logs. Do you see any errors there?

Thanks,
Ayush Gupta

**Comment by ysl208** [comment]
oh, yeah there are: 

The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. [ http://localhost:9080/ | localhost:9080 ] 
ReferenceError: customElements is not defined [Learn More] 


De: "Ayush Gupta" <notifications@github.com> 
À: "ayushgp/web-components-tutorial" <web-components-tutorial@noreply.github.com> 
Cc: "ying-siu liang" <ying-siu.liang@univ-grenoble-alpes.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 17 Mai 2018 20:03:27 
Objet: Re: [ayushgp/web-components-tutorial] 'Forbidden' when running static-server (#4) 

I meant the browser console logs. Do you see any errors there? 

Thanks, 
Ayush Gupta

**Comment by ayushgp** [comment]
This is coming because your browser doesn't support custom elements. Try
using chrome. You can learn more about how to get customelements working
here: https://stackoverflow.com/q/40677265/3719089

This is most likely a browser specific issue. It'd be easier for you if you
could just use chrome.

Thanks,
Ayush Gupta

**Comment by ysl208** [comment]
got it - it works in chrome. Thanks! 


De: "Ayush Gupta" <notifications@github.com> 
À: "ayushgp/web-components-tutorial" <web-components-tutorial@noreply.github.com> 
Cc: "ying-siu liang" <ying-siu.liang@univ-grenoble-alpes.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 17 Mai 2018 20:41:49 
Objet: Re: [ayushgp/web-components-tutorial] 'Forbidden' when running static-server (#4) 

This is coming because your browser doesn't support custom elements. Try 
using chrome. You can learn more about how to get customelements working 
here: https://stackoverflow.com/q/40677265/3719089 

This is most likely a browser specific issue. It'd be easier for you if you 
could just use chrome. 

Thanks, 
Ayush Gupta
